project:
  type: website
  output-dir: docs

website:
  title: "iJustin"
  navbar:
    left:
      - href: about.qmd
        text: "â˜ğŸ»"
      - href: publications.qmd
        text: Publications
      - href: CV.pdf
        text: CV
      - text: "âš™ï¸"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
