project:
  type: website
  output-dir: docs

website:
  title: "iJustin"
  navbar:
    left:
      - href: CV.pdf
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
